<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
      https://maven.apache.org/xsd/maven-4.0.0.xsd">


<modelVersion>4.0.0</modelVersion>

<groupId>com.tidalai</groupId>
<artifactId>tidalai</artifactId>
<version>0.1.0</version>
<name>TidalAI</name>
<description>Local AI Agent Dashboard</description>

<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>27</maven.compiler.release>

    <javafx.version>25.0.1</javafx.version>
    <jackson.version>2.20.0</jackson.version>

    <maven.compiler.plugin.version>3.14.1</maven.compiler.plugin.version>
    <javafx.maven.plugin.version>0.0.8</javafx.maven.plugin.version>
    <maven.dependency.plugin.version>3.8.1</maven.dependency.plugin.version>
</properties>

<dependencies>

    <!-- JavaFX -->
    <dependency>
        <groupId>org.openjfx</groupId>
        <artifactId>javafx-controls</artifactId>
        <version>${javafx.version}</version>
    </dependency>

    <dependency>
        <groupId>org.openjfx</groupId>
        <artifactId>javafx-fxml</artifactId>
        <version>${javafx.version}</version>
    </dependency>

    <!-- Jackson -->
    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>${jackson.version}</version>
    </dependency>

</dependencies>

<build>
    <plugins>

        <!-- Java compiler -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>${maven.compiler.plugin.version}</version>
            <configuration>
                <release>${maven.compiler.release}</release>
            </configuration>
        </plugin>

        <!-- JavaFX -->
        <plugin>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-maven-plugin</artifactId>
            <version>${javafx.maven.plugin.version}</version>
            <configuration>
                <mainClass>
                    com.tidalai.Main
                </mainClass>
            </configuration>
        </plugin>

        <!-- Copy runtime dependencies for jpackage -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>${maven.dependency.plugin.version}</version>
        </plugin>

    </plugins>
</build>


</project>
